
CFLAGS		:= -Wall -Wextra -Werror -O3 -msse -msse2 -mfpmath=sse -ftree-vectorize -fPIC
#CFLAGS		:= -Wall -Wextra -Werror -g -fPIC

LIB_PREFIX	:= lib
LIB_EXT	        := .a

MAKEFILE_EXT    := .linux

include Makefile.inc


